brother-hl2220: Fix the filter once and for all (fingers crossed)
Signed-off-by: Peter O'Connor <peter@solus-project.com>

diff --git a/packages/b/brother-hl2220/files/0001-Fix-build-files.patch b/packages/b/brother-hl2220/files/0001-Fix-build-files.patch
--- a/packages/b/brother-hl2220/files/0001-Fix-build-files.patch
+++ b/packages/b/brother-hl2220/files/0001-Fix-build-files.patch
@@ -1,4 +1,4 @@
-From b51439872011bac998f99daf7577985f05960015 Mon Sep 17 00:00:00 2001
+From c189721f481c23f365ca73505acde3bc5f2d08a1 Mon Sep 17 00:00:00 2001
 From: Peter O'Connor <peter@solus-project.com>
 Date: Sat, 24 Mar 2018 14:55:01 +1100
 Subject: [PATCH] Fix build files
@@ -317,13 +317,13 @@ index a28c262..984979f 100755
 -  exit 0 
 diff --git a/brlpdwrapperHL2220 b/brlpdwrapperHL2220
 new file mode 100755
-index 0000000..0abec8d
+index 0000000..6327067
 --- /dev/null
 +++ b/brlpdwrapperHL2220
 @@ -0,0 +1,159 @@
 +#! /bin/sh
 +#
-+# Brother Print filter  >>  $brotherlpdwrapper
++# Brother Print filter  >>  brlpdwrapperHL2220
 +# Copyright (C) 2005 Brother. Industries, Ltd.
 +#                                    Ver1.00
 +
@@ -350,136 +350,136 @@ index 0000000..0abec8d
 +errorcode=0
 +
 +set +o noclobber
-+if [ "\`echo \$5 | grep 'debug-noprint=1'\`" != '' ]; then
++if [ "`echo $5 | grep 'debug-noprint=1'`" != '' ]; then
 +    DEBUG=1
 +fi
-+if [ "\`echo \$5 | grep 'debug-noprint=2'\`" != '' ]; then
++if [ "`echo $5 | grep 'debug-noprint=2'`" != '' ]; then
 +    DEBUG=2
 +fi
-+if [ "\`echo \$5 | grep 'debug-noprint=3'\`" != '' ]; then
++if [ "`echo $5 | grep 'debug-noprint=3'`" != '' ]; then
 +    DEBUG=3
 +fi
-+if [ \$DEBUG != 0 ]; then
++if [ $DEBUG != 0 ]; then
 +    LOGFILE=/tmp/br_cupsfilter_debug_log
 +fi
 +
 +PRINTER=HL2220
 +
 +
-+if [ "\$PPD" = "" ]; then
++if [ "$PPD" = "" ]; then
 +    PPD="/usr/share/cups/model/HL2220.ppd"
 +fi
 +
 +
-+if [ \$LOGFILE != "/dev/null" ]; then
-+  if [ \$LOG_LATESTONLY == "1" ]; then
-+    rm -f \$LOGFILE
-+    date                                                           >\$LOGFILE
++if [ $LOGFILE != "/dev/null" ]; then
++  if [ $LOG_LATESTONLY == "1" ]; then
++    rm -f $LOGFILE
++    date                                                           >$LOGFILE
 +  else
-+    if [ -e \$LOGFILE ]; then
-+	    date                                                        >>\$LOGFILE
++    if [ -e $LOGFILE ]; then
++	    date                                                        >>$LOGFILE
 +    else
-+	    date                                                        >\$LOGFILE
++	    date                                                        >$LOGFILE
 +    fi
 +  fi
-+    echo "arg0 = \$0"                                           >>\$LOGFILE
-+    echo "arg1 = \$1"                                           >>\$LOGFILE
-+    echo "arg2 = \$2"                                           >>\$LOGFILE
-+    echo "arg3 = \$3"                                           >>\$LOGFILE
-+    echo "arg4 = \$4"                                           >>\$LOGFILE
-+    echo "arg5 = \$5"                                           >>\$LOGFILE
-+    echo "arg6 = \$6"                                           >>\$LOGFILE
-+    echo "PPD  = \$PPD"                                         >>\$LOGFILE
++    echo "arg0 = $0"                                           >>$LOGFILE
++    echo "arg1 = $1"                                           >>$LOGFILE
++    echo "arg2 = $2"                                           >>$LOGFILE
++    echo "arg3 = $3"                                           >>$LOGFILE
++    echo "arg4 = $4"                                           >>$LOGFILE
++    echo "arg5 = $5"                                           >>$LOGFILE
++    echo "arg6 = $6"                                           >>$LOGFILE
++    echo "PPD  = $PPD"                                         >>$LOGFILE
 +fi
 +
-+INPUT_TEMP_PS=\`mktemp /tmp/br_input_ps.XXXXXX\`
++INPUT_TEMP_PS=`mktemp /tmp/br_input_ps.XXXXXX`
 +
 +nup="cat"
-+if [ "\`echo \$5 | grep 'Nup='\`" != '' ] && [ \$NUPENABLE != 0 ]; then
++if [ "`echo $5 | grep 'Nup='`" != '' ] && [ $NUPENABLE != 0 ]; then
 +
-+	if   [ "\`echo \$5 | grep 'Nup=64'\`" != '' ]; then
++	if   [ "`echo $5 | grep 'Nup=64'`" != '' ]; then
 +		nup="psnup -64"
-+	elif [ "\`echo \$5 | grep 'Nup=32'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=32'`" != '' ]; then
 +		nup="psnup -32"
-+	elif [ "\`echo \$5 | grep 'Nup=25'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=25'`" != '' ]; then
 +		nup="psnup -25"
-+	elif [ "\`echo \$5 | grep 'Nup=16'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=16'`" != '' ]; then
 +		nup="psnup -16"
-+	elif [ "\`echo \$5 | grep 'Nup=8'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=8'`" != '' ]; then
 +		nup="psnup -8"
-+	elif [ "\`echo \$5 | grep 'Nup=6'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=6'`" != '' ]; then
 +		nup="psnup -6"
-+	elif [ "\`echo \$5 | grep 'Nup=4'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=4'`" != '' ]; then
 +		nup="psnup -4"
-+	elif [ "\`echo \$5 | grep 'Nup=2'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=2'`" != '' ]; then
 +		nup="psnup -2"
-+	elif [ "\`echo \$5 | grep 'Nup=1'\`" != '' ]; then
++	elif [ "`echo $5 | grep 'Nup=1'`" != '' ]; then
 +		nup="cat"
 +	fi
-+	echo   "NUP=\$nup"                                      >>\$LOGFILE
++	echo   "NUP=$nup"                                      >>$LOGFILE
 +   if [ -e /usr/bin/psnup ]; then
-+       if [ \$# -ge 7 ]; then
-+	       cat \$6  | \$nup > \$INPUT_TEMP_PS
++       if [ $# -ge 7 ]; then
++	       cat $6  | $nup > $INPUT_TEMP_PS
 +       else
-+	       cat       | \$nup > \$INPUT_TEMP_PS
++	       cat       | $nup > $INPUT_TEMP_PS
 +       fi
 +   else
-+       if [ \$# -ge 7 ]; then
-+	       cp \$6  \$INPUT_TEMP_PS
++       if [ $# -ge 7 ]; then
++	       cp $6  $INPUT_TEMP_PS
 +       else
-+	       cat    > \$INPUT_TEMP_PS
++	       cat    > $INPUT_TEMP_PS
 +       fi
 +   fi
 +else
-+   if [ \$# -ge 7 ]; then
-+      cp \$6  \$INPUT_TEMP_PS
++   if [ $# -ge 7 ]; then
++      cp $6  $INPUT_TEMP_PS
 +   else
-+      cat    > \$INPUT_TEMP_PS
++      cat    > $INPUT_TEMP_PS
 +   fi
 +fi
 +
-+if [ "\$ENABLECOPY" != 0 ];then
-+  if [ "\$4" -ge 2 ];then
-+     options="\$5"" ""Copies=\$4"
++if [ "$ENABLECOPY" != 0 ];then
++  if [ "$4" -ge 2 ];then
++     options="$5"" ""Copies=$4"
 +  else
-+     options="\$5"
++     options="$5"
 +  fi
 +else
-+  options="\$5"
++  options="$5"
 +fi
 +
 +
-+if [ -e "/usr/local/Brother/Printer/\$PRINTER/lpd/filter\$PRINTER" ]; then
++if [ -e "/usr/local/Brother/Printer/$PRINTER/lpd/filter$PRINTER" ]; then
 +       :
 +else
-+    echo "ERROR: /usr/local/Brother/Printer/\$PRINTER/lpd/filter\$PRINTER does not exist"   >>\$LOGFILE
++    echo "ERROR: /usr/local/Brother/Printer/$PRINTER/lpd/filter$PRINTER does not exist"   >>$LOGFILE
 +    errorcode=30
 +    exit $errorcode
 +fi
 +
 +if [ -e "/usr/local/Brother/Printer/HL2220/cupswrapper/brcupsconfig4" ]; then
-+  if [ \$DEBUG = 0 ]; then
-+     /usr/local/Brother/Printer/HL2220/cupswrapper/brcupsconfig4  \$PRINTER  \$PPD 0 "\$options" >> /dev/null
++  if [ $DEBUG = 0 ]; then
++     /usr/local/Brother/Printer/HL2220/cupswrapper/brcupsconfig4  $PRINTER  $PPD 0 "$options" >> /dev/null
 +  else
-+     /usr/local/Brother/Printer/HL2220/cupswrapper/brcupsconfig4  \$PRINTER  \$PPD \$LOGCLEVEL "\$options" >>\$LOGFILE
++     /usr/local/Brother/Printer/HL2220/cupswrapper/brcupsconfig4  $PRINTER  $PPD $LOGCLEVEL "$options" >>$LOGFILE
 +  fi
 +fi
 +
 +
-+if [ \$DEBUG -le 2 ]; then
-+    cat    \$INPUT_TEMP_PS | /usr/local/Brother/Printer/\$PRINTER/lpd/filter\$PRINTER
++if [ $DEBUG -le 2 ]; then
++    cat    $INPUT_TEMP_PS | /usr/local/Brother/Printer/$PRINTER/lpd/filter$PRINTER
 +fi
 +
-+if [ \$DEBUG -ge 2 ];  then
-+	   if [ \$LOGFILE != "/dev/null" ]; then
-+	     echo ""                                                >>\$LOGFILE
-+	     echo "    ------PostScript Data-------"                >>\$LOGFILE
-+	     cat    \$INPUT_TEMP_PS                                  >>\$LOGFILE
++if [ $DEBUG -ge 2 ];  then
++	   if [ $LOGFILE != "/dev/null" ]; then
++	     echo ""                                                >>$LOGFILE
++	     echo "    ------PostScript Data-------"                >>$LOGFILE
++	     cat    $INPUT_TEMP_PS                                  >>$LOGFILE
 +	   fi
 +fi
-+rm -f  \$INPUT_TEMP_PS
++rm -f  $INPUT_TEMP_PS
 +
-+exit \$errorcode
++exit $errorcode
 diff --git a/usr/local/Brother/Printer/HL2220/lpd/psconvert2 b/usr/local/Brother/Printer/HL2220/lpd/psconvert2
 index b0668a6..2cb2e5a 100755
 --- a/usr/local/Brother/Printer/HL2220/lpd/psconvert2
