gstreamer-1.0-plugins-base: Update to v1.24.1
Release notes:
- [1.24.1](https://gstreamer.freedesktop.org/releases/1.24/#1.24.1)

Signed-off-by: Reilly Brogan <reilly@reillybrogan.com>

diff --git a/packages/g/gstreamer-1.0-plugins-base/package.yml b/packages/g/gstreamer-1.0-plugins-base/package.yml
--- a/packages/g/gstreamer-1.0-plugins-base/package.yml
+++ b/packages/g/gstreamer-1.0-plugins-base/package.yml
@@ -1,8 +1,8 @@
 name       : gstreamer-1.0-plugins-base
-version    : 1.24.0
-release    : 56
+version    : 1.24.1
+release    : 57
 source     :
-    - https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.24.0.tar.xz : f33774129c437e2207034f8927af4cf7ed8c0f006a4602b5cde2823ec6c0cc07
+    - https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.24.1.tar.xz : 884045d1d7c5d6bb8605e45c7ee0e9f1341888e81c2b7c42dff52bb98ede8ec3
 license    : LGPL-2.0-or-later
 component  : multimedia.gstreamer
 homepage   : https://gstreamer.freedesktop.org
@@ -32,9 +32,13 @@ builddeps  :
     - pkgconfig(wayland-protocols)
 checkdeps  :
     - xorg-server-xvfb
+clang      : yes
+optimize   : thin-lto
 setup      : |
     if [[ -n "${EMUL32BUILD}" ]]; then
-        CONFIGURE_OPTIONS="-Dintrospection=disabled -Dgl-graphene=disabled"
+        CONFIGURE_OPTIONS="-Dintrospection=disabled -Dgl-graphene=disabled -Dtests=disabled"
+    else
+        CONFIGURE_OPTIONS="-Dtests=enabled"
     fi
 
     %meson_configure -Dpackage-name="GStreamer Base Plugins ${version} Solus" \
@@ -48,6 +52,7 @@ build      : |
 install    : |
     %ninja_install
 check      : |
+    # This fails in elements_textoverlay for an unknown issue. There are other tests that fail but they require switching to gst-devtools
     export XDG_RUNTIME_DIR="$(mktemp -p $(pwd) -d xdg-runtime-XXXXXX)"
     export MESA_SHADER_CACHE_DIR=$XDG_RUNTIME_DIR/.cache
-    GST_GL_WINDOW=x11 xvfb-run %ninja_check || cat solusBuildDir/meson-logs/testlog.txt
+    LIBGL_ALWAYS_SOFTWARE=true xvfb-run -s '-nolisten local' meson test -C solusBuildDir --print-errorlogs -t 5 || true
