coreutils: Update to 8.32
**Summarized Changelog:**

- Behavior Changes
 - Several programs now check that numbers end properly. For example, 'du -d 1x' now reports an error instead of silently ignoring the 'x'. Affected programs and options include du -d, expr's numeric operands on non-GMP builds, install -g and -o, ls's TABSIZE environment variable, mknod b and c, ptx -g and -w, shuf -n, and sort --batch-size and --parallel.
 - date now parses military time zones in accordance with common usage: "A" to "M"  are equivalent to UTC+1 to UTC+12, "N" to "Y" are equivalent to UTC-1 to UTC-12, "Z" is "zulu" time (UTC).
 - date now pads nanoseconds on the right, not the left.  For example, if the time is currently 1590020079.003388470 seconds after the Epoch, then "date '+%s.%-N'" formerly output "1590020079.3388470", and it now outputs "1590020079.00338847".
 - ls issues an error message on a removed directory. Previously no error and no entries were output, and so indistinguishable from an empty directory, with default ls options.
- Fixes
 - dd conv=fdatasync no longer reports a "Bad file descriptor" error when fdatasync is interrupted, and dd now retries interrupted calls to close, fdatasync, fstat and fsync instead of incorrectly reporting an "Interrupted system call" error.
 - df now correctly parses the /proc/self/mountinfo file for unusual entries
 - rmdir --ignore-fail-on-non-empty now works correctly for directories that fail to be removed due to permission issues.  Previously the exit status was reversed, failing for non empty and succeeding for empty directories.
- Improvements
 - stat and ls now use the statx() system call where available, which can operate more efficiently by only retrieving requested attributes.
- New Features
 - ls now supports the --time=birth option to display and sort by file creation time, where available.

diff --git a/packages/c/coreutils/package.yml b/packages/c/coreutils/package.yml
--- a/packages/c/coreutils/package.yml
+++ b/packages/c/coreutils/package.yml
@@ -1,33 +1,24 @@
 name       : coreutils
-version    : '8.31'
-release    : 23
+version    : '8.32'
+release    : 24
 source     :
-    - https://ftp.gnu.org/gnu/coreutils/coreutils-8.31.tar.xz : ff7a9c918edce6b4f4b2725e3f9b37b0c4d193531cac49a48b56c4d0d3a9e9fd
-license    :
-    - GPL-3.0-or-later
-summary    : GNU core utilities
+    - https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz : 4458d8de7849df44ccab15e16b1548b285224dbba5f08fac070c1c0e0bcc4cfa
+license    : GPL-3.0-or-later
 component  : system.base
+summary    : GNU core utilities
 description: |
-    This package contains the basic file, shell and text manipulation
-    utilities which are expected to exist on every operating system.
-
-    Specifically, this package includes:
-    arch base64 basename cat chcon chgrp chmod chown chroot cksum comm cp
-    csplit cut date dd df dir dircolors dirname du echo env expand expr
-    factor false flock fmt fold groups head hostid id install join link ln
-    logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc od
-    paste pathchk pinky pr printenv printf ptx pwd readlink rm rmdir runcon
-    sha*sum seq shred sleep sort split stat stty sum sync tac tail tee test
-    timeout touch tr true truncate tsort tty uname unexpand uniq unlink
-    users vdir wc who whoami yes
+    This package contains the basic file, shell and text manipulation utilities which are expected to exist on every operating system.
 builddeps  :
     - acl-devel
     - attr-devel
+    - gdb # used in test suite
+    - strace # used in test suite
+    - valgrind # used in test sutie
 optimize   :
     - speed
     - lto
 setup      : |
-    %patch -p1 < $pkgfiles/coreutils-8.27-i18n-1.patch
+    %apply_patches
 
     export FORCE_UNSAFE_CONFIGURE=1
     %reconfigure --enable-largefile \
@@ -50,8 +41,9 @@ install    : |
         ln -sv ../../bin/$linkage $installdir/usr/bin/$linkage
     done
 check      : |
-    # FAIL: tests/tail-2/inotify-dir-recreate
-    # FAIL: tests/misc/nice
-    # FAIL: tests/rm/no-give-up
+    # There are numerous failures which are related to fakeroot preload errors,
+    # permission issues related to being in a chroot, mount issues related to being in a chroot,
+    # failures related to attempting to chroot while in a chroot, etc.
+    # Don't fail the build because of these test failures. For noted failures, see NOTED-FAILS.md
 
-    #make check
+    %make check-very-expensive || :
